apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: kubernetes-dashboard
  namespace: istio-system
spec:
  secretName: kubernetes-dashboard-tls
  issuerRef:
    name: letsencrypt-prod-istio
    kind: ClusterIssuer
  commonName: dashboard.example.com
  dnsNames:
    - dashboard.example.com
